### ISSUE TITLE
Add extension JS file to release assets

### ISSUE THREAD

**Issue by kaklakariada** [exasol/oracle-virtual-schema#45]
Release https://github.com/exasol/oracle-virtual-schema/releases/tag/3.0.0 added support for the extension manager. However the extension JS file is currently not published as a release asset.

```[tasklist]
### Tasks
- [x] Publish extension JS file as release artifact
- [ ] Add extension to https://github.com/exasol/extension-manager/blob/main/registry-upload/src/common.ts#L10
- [ ] Publish new registry for test & prod
```
